services:
  backend:
    build: ./PostsAPI
    container_name: posts-api
    ports:
      - "5000:5000"
    environment: 
      - MONGO_URL=mongodb://mongodb:27017/mongo_db
      - NODE_ENV=development
    depends_on:
      - mongo-server
    networks:
      - mongodb_network
  frontend:
    build: ./posts-app
    container_name: posts-app
    ports:
      - "3000:3000"
    environment: 
      - VITE_API_URL=http://127.0.0.1:5555/api/posts
    depends_on:
      - backend
    networks:
      - mongodb_network
  # mongo-server:
  #   image: mongo:latest
  #   container_name: mongo-server
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - mongodb_network
  # mongo-client:
  #   image: mongo-express:latest
  #   container_name: mongo-client
  #   restart: always
  #   depends_on:
  #     - mongo-server
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo-server
  #     - ME_CONFIG_MONGODB_PORT=27017
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - mongodb_network
volumes:
  mongodb_data:
networks:
  mongodb_network: