apiVersion: v1
kind: Service
metadata:
  name: k8s-backend-service
spec:
  selector:
    app: k8s-backend
  ports:
    - port: 5555
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-frontend-service
spec:
  selector:
    app: k8s-frontend
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3000
  type: LoadBalancer